import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import {io} from 'socket.io-client';

const inter = Inter({ subsets: ['latin'] })

let socket;


export default function Home() {


  const [conversa, setConversa] = useState([]);
  const [hasLoading, setHasLoading] = useState(false);
  const [texto, setTexto] = useState("");


  useEffect(()=>{
    load()

  },[])

    function load(){
    console.log("Otniel")

      if (!localStorage.getItem("nome")) {
        const nome = window.prompt("Insira seu nome:");
        const id = window.prompt("Insira seu id:");
        localStorage.setItem("nome", nome);
        localStorage.setItem("id", id);
    
    }
       
    socket = io("http://127.0.0.1:5000");

    socket.emit("todaConversa", ()=>{
           
    })

    socket.on("pegaConversa", (dados)=>{
        setConversa(dados);
    })

    socket.on("getMessage", (msg) =>{
      console.log("antes ");
      console.log(conversa);

        setConversa(conversa.concat(msg));
      
        console.log("depois ");
        console.log(conversa);

    })
    }
      
    function onclick(){
        const mensagem = {
                pessoa_nome: localStorage.getItem("nome"), 
                id_pessoa: localStorage.getItem("id"),
                id_mensagem: "",
                texto: texto
            }
        socket.emit('message',{
            mensagem:mensagem,
            pessoa: localStorage.getItem("id")
            
        })
    }

        
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.chat}>
              <h1 className={styles.h1}>Chat</h1>
              <div className={styles.conversa}>
                {
                  conversa.map((mensagem)=>{
                    if (mensagem.id_pessoa == localStorage.getItem("id")) {
                      return (
                        <p className={styles.mensagem_direita}>{mensagem.texto} :<strong>{mensagem.pessoa_nome}</strong></p>
                        )
                    }

                    return (
                    <p className={styles.mensagem_esquerda}><strong>{mensagem.pessoa_nome}</strong>: {mensagem.texto}</p>
                    )
                  })
                }

              </div>

          </div>

          <div className={styles.comandos}>
              <form className={styles.form} onSubmit={(event)=>{
                event.preventDefault();
                onclick();
              }}>
                  <input className={styles.input} type="text" onChange={(value)=>{
                    setTexto(value.target.value);
                  }}/>
                  <button className={styles.button} id="botao" type="submit">Enviar</button>
              </form>
              

          </div>
        </div>

        
      </main>
    </>
  )
}
